name: End-to-End Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      # Run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Upload Cypress Artifacts
        uses: actions/upload-artifact@v4
        if: failure() # Upload logs only if tests fail
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        if: failure() # Upload logs only if tests fail
        with:
          name: cypress-videos
          path: cypress/videos
